name: CI Audit and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint pytest

      - name: Run Linting
        run: |
          # Lint each agent script; adjust paths as needed.
          pylint Agents/1_Content_Research_Agent/code/content_research_agent.py

      - name: Run Tests
        run: |
          # Run your tests if you have them; if not, you can run your script as a test.
          pytest
